### ISSUE TITLE
Run Travis on Bioconductor version

### ISSUE THREAD

**Issue by BenBarnard** [gabrielodom/pathwayPCA#1]
You should set your travis up to run against the bioconductor check as opposed to the cran check.

**Comment by gabrielodom** [comment]
How do I do that?

**Comment by BenBarnard** [comment]
Instead of devel or release for r you would put bioc-release or bioc-devel.

**Comment by gabrielodom** [comment]
The package passes checks on bioc-release and bioc-devel (as of 1 May 2018).
