### ISSUE TITLE
SuperPCA_pVals() Issues

### ISSUE THREAD

**Issue by gabrielodom** [gabrielodom/pathwayPCA#12]
James discovered that the p-values from Supervised PCA do not follow the expected uniform(0,1) distribution. This issue thread will be where I keep track of any problems I find in the internal functions of `SuperPCA_pVals()`.

**Comment by gabrielodom** [comment]
**Sub-Issue 1:**
In the internal `superpc.st()` function, the `if {} else {}` on lines 104-123, `else` section, sort the t-scores for each gene instead of the absolute value of the t-scores.

Also, line 109 replaces any t-score greater than the 1 - 5 / p quantile with that quantile. This pulls in the upper tail, but the lower tail is left completely untouched. Why?

**Comment by gabrielodom** [comment]
**Sub-Issue 2**:
The internal `pathway_tScores()` function (which calls the `superpc.st` function) returns a matrix of `numPCs` by `n.threshold`. When we apply over the list of pathways, the `parSapply()` function turns this into a 1 by (`numPCs` by `n.threshold`) vector. Same for the `pathway_tControl()` function. I still don't know if this is an issue or not.

**Comment by gabrielodom** [comment]
**Sub-Issue 3**:
The `weibullMix_optimParams()` function returns distribution parameter estimates that don't really align with the control t-score that I see. The returned "optimal" parameters are:
    
             p        mu1         s1        mu2         s2 
     0.5117412 -0.2669582  0.5995982 -0.1999984  0.5952266

However, when I estimate the mean of the negative values and positive values, I get -2.087 and 2.033, respectively. Obviously, I'm not understanding something about the Gumbel Extreme Value Mixture distribution, or the `optim` function is getting stuck in a local maxima.

When I estimate this as a mixture of normals (which is *really* close by the way), I get these estimates:

    summary of normalmixEM object:
              comp 1   comp 2
    lambda  0.495997 0.504003
    mu     -2.125007 2.018218
    sigma   0.738101 0.742846
    loglik at estimate:  -2081.728

EDIT: I have compared the pdf of the Gumbel to the one in Chen et al. (2010) and confirmed that it is coded correctly in `weibullMix_optimParams` (I can't confirm the gradient because it's not in the paper to my knowledge).

**Comment by gabrielodom** [comment]
**Partial Solution**:
I now understand why the p-values do not cover the range (0,1). In the `weibullMix_pValues()` function, we take the minimum of the p-value and 1 - p-value. This is why the p-values appear truncated at 0.5. However, this does not explain why the distribution is still heavy on the left side for data that is truly noise.

**Comment by gabrielodom** [comment]
**Sub-Issue 4**:
The probability distribution in the Chen et al. (2010) paper is as follows:

$$
p * e ^{ -exp( -t_1 ) } + ( 1 - p ) * ( 1 - e ^ { -exp( t_2 ) } )
$$

However, we have it coded with a negative on t_2 and a positive on t_1.

EDIT: fixing this made the p-values worse (the distribution of the noise p-values was more skewed)???

EDIT2: I "fixed" things the wrong way, so I corrected what I had done and applied a proper fix. Now, the p-values are back to the same skewed distribution as before. But at least the distribution isn't *more* skewed...

For completeness (even though I know it will be in the commit), here is what I changed:

    OLD
    78    arg_A <- -(tScore_vec - abCounts_ls$bn - optimParams_vec["mu1"]) * an_s1
    79    A <- 1 - exp(-exp(arg_A)) # in [0, 1]
    82    arg_B <- (tScore_vec + abCounts_ls$bn + optimParams_vec["mu2"]) * an_s2
    83    B <- exp(-exp(arg_B)) # also in [0, 1]
    NEW
    78    t_1 <- (tScore_vec - abCounts_ls$bn - optimParams_vec["mu1"]) * an_s1
    79    A <- exp(-exp(-t_1)) # in [0, 1]
    82    t_2 <- (tScore_vec + abCounts_ls$bn + optimParams_vec["mu2"]) * an_s2
    83    B <- 1 - exp(-exp(t_2)) # also in [0, 1]

**Comment by gabrielodom** [comment]
**More Information**:
While digging around in the Gumbel distribution stuff, I calculated the empirical CDF from the control t-scores. It should be that (even if the Extreme Value distribution stuff is screwed up) the quantiles of the empirical CDF should still give me good p-values. *They don't.*

This leads me to believe (and also that I've gone over the Weibull equations with a fine-tooth comb) that the issue is in the calculation of the control t-scores (via `pathway_tControl`). Otherwise, I should at least be able to get uniform-ish p-values from the emprical distribution.

**Comment by lxw391** [comment]
try different random outcomes for each pathway to generate the null distribution

**Comment by gabrielodom** [comment]
When I wrote the random sampling function, I included a nonparametric option for AES-PCA (which makes sense because that method has some predefined number of permutations). Unfortunately, I did not change the default to this function call for Supervised PCA, resulting in an incorrect null distribution. The p-values from Supervised PCA are now correct.
