### ISSUE TITLE
Inspecting top pathways

### ISSUE THREAD

**Issue by gabrielodom** [gabrielodom/pathwayPCA#16]
From Lily:

- correlate each gene with first SPCA
- do a barplot for top pathway
- return a vector per top pathway with the most strongly correlated genes

In 2008 SPCA paper, there is an example figure for the barplot

**Comment by gabrielodom** [comment]
Wait for this until Issue #9 is completed. We will need the updated function outputs to do this.

**Comment by gabrielodom** [comment]
Also, @jamesban2015 gave the suggestion to add a slot for the top genes per pathway.

**Comment by gabrielodom** [comment]
Issue #9 is closed, so you can move forward with this @jamesban2015.

**Comment by lxw391** [comment]
LW - I looked at the SPCA paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732277/

Fig 2 presents the loadings of first PC, so please just do loadings for first PC

**Comment by gabrielodom** [comment]
Add James' function to the vignette. Add an option to the function for correlation or loadings. Default to correlation.

**Comment by jamesban2015** [comment]
code and examples for plotting PC loading and correlation are available at dropbox: Ban and Odom - Bioconductor Package/James_testing/Topgene_plots

**Comment by gabrielodom** [comment]
Please take a look at the graphs in `Topgene_plots/Plots`. I will be adding the function `BarChartPCs()` to one of the vignettes. I also need to add a function to extract the PCs and Loadings from an `*pcout` object by pathway name or pathway ID.

See Issue #51

**Comment by gabrielodom** [comment]
I have drafts for the Loadings and Correlations bar chart graphing functions in `Topgene_plots/Odom_plot_gene_barchart_edit_20181120.R`. These functions are 

1. `PathwayBarChart()` - takes in a tidy data frame and plots it.
2. `BarChartPCs()` - tidys Loadings vector and calls `PathwayBarChart()`
2. `BarChartCorrPCs()` - finds correlation between genes in the pathway and the recorded levels for those genes and calls `PathwayBarChart()`

**Comment by gabrielodom** [comment]
Function names changed:

1. `BarChartPCs` -> `TidyLoading`
2. `BarChartCorrPCs` -> `TidyCorrelation`

**Comment by gabrielodom** [comment]
@lxw391, please see the edits to the `pathwayPCA_Users_Guide`

**Comment by lxw391** [comment]
@gabrielodom which document did the `TidyCorrelation` function got moved to?

and where is the visualization vignette?

**Comment by gabrielodom** [comment]
@lxw391: `TidyLoading()` and `TidyCorrelation()`  were moved to the visualization vignette: `inst/supplmentary_vignettes/C5-Analyse_and_Visualize_Results.Rmd`
