### ISSUE TITLE
Modify the help page of extract_aesPCs

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#29]
modify the help page of function "extract_aesPCs" to make it looks more clear that this function can extract both the normal principal components and the aesPCA's principal components.

**Comment by gabrielodom** [comment]
The `AESPCA_pVals()` function now passes the `asPCA` argument to the internal `extract_aesPCs()` function through the `standardPCA` argument. This function then returns either the `oldScore` and `oldLoad` (vanilla PCA) or the `aesScore` and `aesLoad` (AES-PCA) lists.
