### ISSUE TITLE
R CMD check fails on Windows but not Mac

### ISSUE THREAD

**Issue by gabrielodom** [gabrielodom/pathwayPCA#30]
From RStudio Check:

    ==> devtools::check(cleanup = FALSE, args = c('--no-build-vignettes','--no-vignettes'))

    Updating pathwayPCA documentation
    Loading pathwayPCA
    Error in file(con, "r") : cannot open the connection
    Calls: <Anonymous> ... parse_package -> lapply -> FUN -> read_lines -> <Anonymous> -> file
    In addition: Warning messages:
    1: `cleanup` is deprecated 
    2: In file(con, "r") :
      cannot open file 'C:\Users\gjo15\Documents\GitHub\pathwayPCA\R': Permission denied
    Execution halted

    Exited with status 1.

R CMD check pathwayPCA is slightly more informative:

    $ R CMD check pathwayPCA --no-build-vignettes --no-vignettes
    * using log directory 'C:/Users/gjo15/Documents/GitHub/pathwayPCA.Rcheck'
    * using R version 3.5.1 (2018-07-02)
    * using platform: x86_64-w64-mingw32 (64-bit)
    * using session charset: ISO8859-1
    * using options '--no-vignettes --no-build-vignettes'
    * checking for file 'pathwayPCA/DESCRIPTION' ... ERROR
    Required field missing or empty:
      'Author'
    * DONE

    Status: 1 ERROR

This issue started after I updated all of my packages last Friday. The `DESCRIPTION` file hasn't changed in ages, so I think this error is a false flag.

Session Info:

    R version 3.5.1 (2018-07-02)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    
    LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] pathwayPCA_0.0.0.9000

    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.18     rstudioapi_0.7   xml2_1.2.0       magrittr_1.5     roxygen2_6.1.0   splines_3.5.1    
    devtools_1.13.6 
     [8] lattice_0.20-35  R6_2.2.2         rlang_0.2.2      stringr_1.3.1    tools_3.5.1      parallel_3.5.1   grid_3.5.1      
    [15] withr_2.1.2      lars_1.2         commonmark_1.5   survival_2.42-6  yaml_2.2.0       digest_0.6.17    
    assertthat_0.2.0
    [22] rprojroot_1.3-2  crayon_1.3.4     Matrix_1.2-14    purrr_0.2.5      memoise_1.1.0    stringi_1.2.4    
    compiler_3.5.1  
    [29] desc_1.2.0       backports_1.1.2

**Comment by gabrielodom** [comment]
@lxw391 can you duplicate this issue on your Windows machine?

**Comment by lxw391** [comment]
https://stackoverflow.com/questions/51641469/roxygen-warning-cannot-open-the-connection-permission-denied

**Comment by gabrielodom** [comment]
I'm now using the development version of `roxygen2` from `devtools::install_github("gustavdelius/roxygen")`. This updated version of `roxygen2` requires you to have Rtools 35 on your system. To install this, follow these steps:
1. Close R
2. Uninstall any previous versions of Rtools
3. Download `Rtools35.exe` from https://cran.r-project.org/bin/windows/Rtools/
4. Follow these steps to ensure that Rtools is installed properly: https://stackoverflow.com/questions/50034966/no-rtools-compatible-with-r-version-3-5-0-was-found
5. Start R, and check that Rtools is in the system path (C:\Rtools\bin) by following this help:
https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows
You should see `C:\\Program Files\\R\\R-3.5.1\\bin\\x64;C:\\Rtools\\bin;` as the first two entries of the system PATH.


Package `pathwayPCA` is now on RoxygenNote `6.1.0.9000` for Windows OS.
