### ISSUE TITLE
'ExtractAESPCs' function modify

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#39]
1. the function help page should have a link to the help page of function 'parallel'.

2. having options (parallel= , numCores=) is not good for people not familiar with 'parallel' package,
    better to add judgement syntax to judge whether use the 'parallel' package.

3. if "(parallel=TRUE, numCores=NULL(default))", it shows error message "**### Error in do.call(c, clusterApplyLB(cl = cl, x = splitList(X, nchunks),  : 
  second argument must be a list ******_"
which is confusing, better to show error message like "missing setting numbers of cores ".

**Comment by gabrielodom** [comment]
Changed the internal default of the `numCores` argument to be the number of available cores - 2. This means that users who are running their code serially do not have to specify `numCores`, but also that users who care about parallel execution do not have to specify `numCores` either. This addresses points 2 and 3.

For point 1, I've added a cross-reference to `parallel::clusterApply()` to both the AESPCA and Supervised PCA wrappers.
