### ISSUE TITLE
function 'CreateOmics' problem

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#41]
seems like the function 'CreateOmics' has changed the raw value of the assayData_df, it used to be all range from 0-1, after running 'CreateOmics', the omics contains data that less than 0 and bigger than 1.

**Comment by lizhongliu1996** [comment]
The r script file and the rds data file are located in the box folder 'Lizhong Liu/new issue'.

**Comment by gabrielodom** [comment]
As we discussed in person, set the `centerScale` parameter to `c(FALSE, FALSE)`.
