### ISSUE TITLE
'ExtractAESPCs' (and getPathPCLs, SubsetPathwayData) functions lost colnames and rownames

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#42]
after run the function 'ExtractAESPCs', the PCs results lost the colnames and rownames of the assay_data

**Comment by gabrielodom** [comment]
To each data frame element of `PCs_ls` (within `SuperPCA_pVals()` and `AESPCA_pVals()`), add the original row names of `assayData_df` (if they exist).

**Comment by gabrielodom** [comment]
Should we add a function that takes in sample-ID-labelled assay and phenotype data? We could then match/join the data ourselves within this function. This would also allow us to avoid rownames altogether.

**Comment by gabrielodom** [comment]
This function is internal. Also, the `getPathPCLs()` function returns gene rownames as needed.

**Comment by lxw391** [comment]
I'm re-opening this issue: 
the gene names are added, but sample names are not, so still needs to add sample names
![image](https://user-images.githubusercontent.com/27868862/49329344-44c65100-f54b-11e8-9fe6-8c7c26fc952c.png)
![image](https://user-images.githubusercontent.com/27868862/49329348-527bd680-f54b-11e8-9c6c-e2db94575e33.png)

**Comment by lxw391** [comment]
Also, would it be possible for getPathPCLs to return more than 1 PC? 
- answer: this would have to be done in function AESPCA_pVals by specifying numPCs parameter

So please add the following sentence to help file of `getPathPCLs`
- "note that to extract more than one PCs, the numPCs parameter in function AESPCA_pvals needs to be modified accordingly"

Question: 
- how might one know which R file has function getPathPCLs?

**Comment by lxw391** [comment]
The sample names is especially important for multiomics analysis. See below, the samples are ordered differently in inputing datasedt, without row names for the samples, it can be error prone to do multi-omics analysis

please also modify the sample columns so that they match in both datasets

![image](https://user-images.githubusercontent.com/27868862/49330654-7ba66200-f55f-11e8-9ce0-cd6b11e1a1d9.png)

**Comment by lxw391** [comment]
For function SubsetPathwayData, could we also add rownames or an extra column for sample IDs?

> CNVgene_df <- SubsetPathwayData(ovCNV_Surv, "path22")

this is what I get currently: 
![image](https://user-images.githubusercontent.com/27868862/49344793-dc11ce00-f649-11e8-9e4e-0e3942a11218.png)

without sample IDs, it's difficult to merge data for multi-omics analysis

**Comment by gabrielodom** [comment]
We will take in a data frame with sample IDs as the first column for the assay data, and a data frame with sample IDs as the first column of the response data. Then, we will internally inner join the two data frames, and preserve the sample IDs.

Gabriel is unhappy with this.

**Comment by gabrielodom** [comment]
Find in a directory: CTRL / CMD + Shift + F

**Comment by gabrielodom** [comment]
This is requiring even more effort than I had originally anticipated. I have to re-write *all* examples and testing scripts to account for the fact that we now require sample IDs for both assay and phenotype. This will take at least a full day to finish, and that doesn't even include the time to rebuild the `OmicsPath` class to now take in the sample IDs or the time to propagate the sample IDs through the code.

**Comment by gabrielodom** [comment]
I need to update the documentation across the board to mention that we require the response object to be a data frame.

**Comment by lxw391** [comment]
@gabrielodom OK, I see. I also thought more about your concern on having createOmics merging datasets for users. 

So how about we keep what we have now, except requiring the first column of the `response` slot in `CreateOmics` to be a variable called `Sample`? this way, CreateOmics can extract sample IDs and pass it on to `getPathPCLs`.

**Comment by gabrielodom** [comment]
`sampleIDs_char` has been added as a slot to all `Omics*` objects. We additionally need `get*()` and `set*()` methods before we can move forward with returning these sample IDs.

**Comment by gabrielodom** [comment]
I wrote the `CheckSampleIDs()` function to help in object creation. Also, I had to make more edits to the `CreateOmics()` function to support these `Omics*`-slot changes.

**Comment by gabrielodom** [comment]
Updates:

- The `SubsetPathwayData()` function now returns a data frame with leading sample IDs column
- The `getPathPCLs()` function now returns the PCs as a tidy data frame with leading sample IDs column and the loadings as a tidy data frame with leading feature IDs column

**Comment by gabrielodom** [comment]
@lizhongliu1996, I think this is finished. Please re-test your code. Note that you will have to supply the sample IDs as the first column of the assay and response data frames, as appropriate.

**Comment by lizhongliu1996** [comment]
I test it with Proteo and CopyNumber dataset, both `SubsetPathwayData()` and `getPathPCLs()` function works, but do notice that when use `CreateOmics()`, the argument  `assayData_df = dataset[, -(2:x)]` should start from 2nd column.

**Comment by gabrielodom** [comment]
Yes, the sample ID column is now required for both the assay and response.
Thanks!!

**Comment by gabrielodom** [comment]
Sample IDs are lost in the `LoadOntoPCs` function.
