### ISSUE TITLE
vignette example - multi-omics analysis - circos plot

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#48]
consider circos plot for pathways identified in both copy number and proteomics datasets. see https://medium.com/@Marianattestad/a-treatise-on-making-circos-plots-from-genomic-data-7ff496849e0

and figure 7 in PARADIGM paper. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2881367/
we can draw the CircleMap for each pathway, since sample specific estimate for each pathway can be estimated for each sample.

**Comment by lizhongliu1996** [comment]
http://shinycircos.ncpgr.cn/
I think this shiny app is a easy and good option to draw  circo plots

**Comment by lizhongliu1996** [comment]
packages available including "circlize, RCircos, CIRCUS, and OmicCircos",  

"RCircos, CIRCUS, and OmicCircos" are designed specially for genomics data which include column named "chromStart" and "chromEnd", circle plot is drawn based on these two columns.

In our multi-omics example, consider to use R package "circlize" 
Reference: https://jokergoo.github.io/circlize_book/book/index.html

Also, try Shirley's code

**Comment by gabrielodom** [comment]
Are these data sets recording samples from the same subjects? From the Vaske et al. (2010) paper: "Each tick in the ring corresponds to a single patient sample while the color corresponds to activated (red), deactivated (blue) or unchanged (white) levels of activity." If we don't know that the same subjects were kept between copy number data and proteomics data, I don't see how we can create circle plots.

@lizhongliu1996, please check the record IDs from the two data sets to ascertain if an overlap exists.

If we cannot join over subject, then perhaps the ticks of each ring can be a pathway. This means, however, that a single-pathway circle plot is not possible to create.

**Comment by lxw391** [comment]
They should be matched samples. Definition for TCGA sample code is at 
https://docs.gdc.cancer.gov/Encyclopedia/pages/TCGA_Barcode/

**Comment by gabrielodom** [comment]
@lizhongliu1996, here is some code to get the pathways and loadings for the RELA gene:
`\Xena Multi-Omics Ovarian\RELA_gene_loadings_20181127.R"`

**Comment by lizhongliu1996** [comment]
![circleplot3](https://user-images.githubusercontent.com/39965417/49745350-c2d1d880-fc6c-11e8-9f9a-b62eb25f578a.jpeg)

**Comment by gabrielodom** [comment]
@lizhongliu1996, ask Shirley for help making the colours continuous.

**Comment by gabrielodom** [comment]
Colour palette: `plot(1:100, col = colorRampPalette(c("red", "white", "blue"))(100), pch = 16)`

Or, to have negative from blue to white: `colorRampPalette(c("blue", "white"))(50)`; and positive from white to red: `colorRampPalette(c("white", "red"))(50)`.

**Comment by lizhongliu1996** [comment]
have a look at this one
![circleplot5](https://user-images.githubusercontent.com/39965417/49823676-41eb0d80-fd4e-11e8-91e4-a1eeab48ec47.jpeg)

**Comment by gabrielodom** [comment]
Good work. Move edits discussions to Issue #49
