### ISSUE TITLE
Vignette Examples edits

### ISSUE THREAD

**Issue by gabrielodom** [gabrielodom/pathwayPCA#49]
This is the continuation of Issue #28. Now that we have the examples written, we will need to enhance, modify, and edit these examples. This is the "catch-all" issue for general vignette example edits.

**Comment by gabrielodom** [comment]
For Example 4 (colorectal prediction): Steven will ponder on the odd shape of the survival ROC curves.
For Example 3 (Multi-omics): See Issue #48, add circle plots (@lizhongliu1996). Remove SuperPCA part (@gabrielodom).
For Example 2 (KIRP interaction): fix table (`aespcaSignifSexInter_df`) to show `terms`, `estimate`, `std.error`, `statistic` and `p.value` columns.

For all examples: can we access data in the vignettes from the internet? See the last comment of Issue #28.

**Comment by gabrielodom** [comment]
As mentioned in Issue #5, we now have a vignette. Thus, this thread will discuss edits to the vignette examples. Edits to the vignette itself will be handled through Word Track Changes.

**Comment by gabrielodom** [comment]
For example 2, I've fixed the tibble display for `aespcaSignifSexInter_df` and `superpcaSignifSexInter_df` within the `KIRP_Sex_PC_Interaction.html` report.

**Comment by gabrielodom** [comment]
For example 3, I've removed the super PCA section. @lizhongliu1996, if you plan to copy your results into the main report, please make any edits to the updated version: `Xena Multi-Omics Ovarian/Reports/summary_ovarian_multiomics.Rmd`

**Comment by gabrielodom** [comment]
@lxw391, in order to include the vignette you are working on, it must have an associated Sweave or Rmarkdown file (see the DESeq2 documentation for an example). Do you want to wait until we have the draft more polished before we build the Rmarkdown file?

**Comment by lxw391** [comment]
yes please edit the word file with track changes. we can build Rmd file after we finalize it.

**Comment by gabrielodom** [comment]
Please see the updated code and figures in `Vignettes/odomEdit_lily_introduction_vignette.docx` in the package Dropbox folder.

**Comment by gabrielodom** [comment]
Change from WnT to IL-1 pathway for ovarian proteomics and copy number.

**Comment by gabrielodom** [comment]
Add the pathway names onto the p-value / FDR columns (see page 4 of NAR draft). This should replace the column graph in chapter 5.

**Comment by gabrielodom** [comment]
@jamesban2015 will attempt to replicate table 1 from in Antonio's TCGAbiolinks paper. We will compare pathwayPCA to GoSeq, GSEA, and EnrichR.

**Comment by gabrielodom** [comment]
I will attempt to replicate figure 2 from in Antonio's TCGAbiolinks paper. Our sections will be

- Data: all functions from chapters 2 and 3
- Analysis: SuperPCA and AESPCA from chapter 4
- Results: all functions from chapter 5

"Check out MindManager or Xmind" - @lizhongliu1996

**Comment by gabrielodom** [comment]
From @lxw391, the remaining tasks for pathwayPCA are:

1. Update vignette to match work in NAR paper (change pathway to IL-1, pick NFKB1 gene) DONE
2. Assemble all figures to a PPT document DONE
3. Edit NAR draft

**Comment by gabrielodom** [comment]
Updated figures are either in the word document (`odomEdit_lily_introduction_vignette.docx`) or in the `Figures/` subdirectory.

**Comment by gabrielodom** [comment]
@lizhongliu1996 and I worked on the powerpoint last night and this morning. We are still missing the Circo plot (from @lizhongliu1996 and Shirley) and the methods comparison table (from @jamesban2015).
This file is `Vignettes/Figures/NAR_draft_figures_20181211.pptx`

@lxw391, please take a look when you get a chance.

**Comment by gabrielodom** [comment]
Added the Circo plot from Issue #48. Since the plot will only need minor edits, we can move the discussion here.

**Comment by gabrielodom** [comment]
I'm editing page 5 of the NAR draft. My comments and changes are in `LWtest/NAR-DRAFT_12-10-2018.docx`

**Comment by gabrielodom** [comment]
I've finished my edits to the NAR draft.

**Comment by gabrielodom** [comment]
Lily's vignette has replaced the "advanced users guide"

**Comment by lxw391** [comment]
@gabrielodom I got an error when running the vignette. Gabriel -- could you look into this? 

![image](https://user-images.githubusercontent.com/27868862/49968439-d347b480-fef3-11e8-9488-3dc10e4a9986.png)

**Comment by gabrielodom** [comment]
Did you pull changes and re-install the package? I’m assuming this is from colonSurv_df?

**Comment by lxw391** [comment]
Ok let me try rebuilding the package first thing tomorrow morning

**Comment by gabrielodom** [comment]
@lizhongliu1996 had an issue with R CMD check. Basically, don't leave the Word output as the default vignette option. Use this option to build the vignette, but then change it back to html.

**Comment by lizhongliu1996** [comment]
That fix the problem!

**Comment by gabrielodom** [comment]
I think we can finally close this monster issue.
