### ISSUE TITLE
AESPCA function - Add Non-Parametric p-Value Option 

### ISSUE THREAD

**Issue by gabrielodom** [gabrielodom/pathwayPCA#50]
Per the PGDAC meeting with Bing's group, Steven mentioned that we should compare the raw (parametric) $p$-values to the permutation $p$-values to see if there is a clear relationship. Thus we need an option to `AESPCA_pVals()` to request the raw $p$-value.

**Comment by gabrielodom** [comment]
See the Identification of DMRs subsection in https://www.nature.com/articles/mp2013114.pdf

**Comment by gabrielodom** [comment]
We have three components to analyse here:

1. CoxPH Model overall p-values (`PermTestSurv()`)
2. GLM overall p-values (`PermTestCateg()`)
3. LM overall p-values (`PermTestReg()`)

Based on the results in the testing files `Test_PermTestSurv_Parametric.R` and `Test_PermTestCateg_Parametric.R`, the Pearson correlation between the raw parametric and raw permutation-based p-values for CoxPH and GLM is very high (0.95 or better, even for 100 replicates). However, the FDRs in the GLM case are not as strongly correlated (0.67 for 100 replicates, 0.85 for 1000). I do not yet have results for the LM case.

**Comment by lxw391** [comment]
@gabrielodom Please update function using `anova(true_mod, test = "LRT")` 

Also please change AIC to anova function instead to perform LRT test.

**Comment by gabrielodom** [comment]
Because this is not related to the *parametric* p-value estimation discussion, I've created a new issue: Issue #57.

**Comment by gabrielodom** [comment]
For the LM, see `Test_PermTestReg_Parametric.R`.

Now, all three methods support parametric p-value estimation. To estimate the pathway p-values parametrically, set `numReps = 0` in the `AESPCA_pVals()` function call. Overall, the raw p-values between the parametric and non-parametric options are nearly perfectly correlated (rho > 0.98 even for 100 replicates).

**Comment by gabrielodom** [comment]
![image](https://user-images.githubusercontent.com/24464126/49402735-a2f45f00-f718-11e8-8650-85ffa0476f28.png)

As we see in the attached image, test size does not appear to be a major concern.
