### ISSUE TITLE
Reference Manual Edits

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#53]
see below, function `SubsetPathwayData` needs an example

![image](https://user-images.githubusercontent.com/27868862/48980911-f9b8c380-f09c-11e8-8af5-25e9f94f017f.png)

**Comment by gabrielodom** [comment]
This function, and `getPathPCLs()` need examples.

**Comment by gabrielodom** [comment]
After making the vignette edits, build the PDF.
@lxw391, please mark any functions you find without examples in this thread.

**Comment by gabrielodom** [comment]
Updated the examples in `getAssay()`, `getPathwayCollection()`, `SubsetPathwayData()`, `getResponse()`, `getEvent()`, `getEventTime()`, `getPathPCLs()`, and `AESPCA_pVals()`.

**Comment by gabrielodom** [comment]
Updated the example in `LoadOntoPCs()`.

**Comment by lxw391** [comment]
@gabrielodom Could you tell me where are the pdf file for the reference manual is located? Thanks.

**Comment by gabrielodom** [comment]
I've rebuilt the help manual. I'll share the pdf on dropbox in the top level of `Ban and Odom -Bioconductor package/`.

Also, I've changed the documentation level of many of the internal functions to "internal" (through the `@keywords` tag). These functions will be excluded from the manual. If you'd like any of these functions to be included, just ask, and I'll remove the tag.

**Comment by gabrielodom** [comment]
Please leave any manual edit requests as comments here.

**Comment by gabrielodom** [comment]
Edits:

- the URLs on the first page should be reversed
- wrong quotes around User Guides
- change documentation names:
    i. getAssay --> SubsetOmicsPath
    ii. getEventTime --> SubsetOmicsSurv
    iii. getResponse --> SubsetOmicsResponse
    iv. [[.pathwayCollection --> SubsetPathwayCollection
- normalize should be internal
- Transpose Assay should ask if the names are in the first column

**Comment by gabrielodom** [comment]
Updated the documentation title of `LoadOntoPCs()`.

**Comment by gabrielodom** [comment]
Closed accidentally in the merge.
