### ISSUE TITLE
AESPCA function output

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#54]
Suggest to take out the "setsize" column, (and maybe renaming "trim_size" to set size), it can be confusing for users. Typically, pathway analysis software returns the total number of genes in the pathway (after trimming) and  number of deferentially expressed genes. 

also why does path110 and path253 have same name, but different genes? 

![image](https://user-images.githubusercontent.com/27868862/48981849-9a60b080-f0a8-11e8-9aa0-f65b2982969f.png)

**Comment by gabrielodom** [comment]
1. Set size vs. trimmed set size: should we report the number of genes removed then? We should have some way of knowing how many of the total features from the pathway were actually used.
2. That's a Wikipathways question. Here's their documentation for
    - `WP75`: https://www.wikipathways.org/index.php/Pathway:WP75
    - `WP3858`: https://www.wikipathways.org/index.php/Pathway:WP3858

**Comment by gabrielodom** [comment]
For q1: remove the `setsize` column. This information is still retained in the `-omics` object. Rename `trim_setsize` to `n_tested`.

For q2: do nothing

**Comment by gabrielodom** [comment]
Change all mention of `trim_size` or `trim_setsize` to `n_tested`.
