### ISSUE TITLE
CreateOmics function messages

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#56]
This is what the function currently has: 
![image](https://user-images.githubusercontent.com/27868862/49295142-fe0d2400-f482-11e8-881e-d67537c94d32.png)

Can we turn this into something more positive? for example: 

Creating object of class OmicsSurv….
The input pathway database included xxx pathways. 
The input assay dataset included xxx unique genes. 

Because pathwayPCA is a self-contained test (PMID: 17303618 ), only genes in both assay data and pathway database are considered for analysis. 
Here, there are xx such genes in both assay and pathway database. 

Only pathways with at least 5 or more genes are tested (specified by minPathSize parameter). 
Here, there are xxx pathways with at least 5 or more genes.

**Comment by gabrielodom** [comment]
I edited these creation messages again...
