### ISSUE TITLE
Website Comments / Edits

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#58]
Please update current title "pathwayPCA: A Bioconductor package for extracting principal components from expressed pathways" at https://gabrielodom.github.io/pathwayPCA/

to 

"PathwayPCA: an R package for integrative pathway analysis with modern PCA methodology and gene selection"

**Comment by gabrielodom** [comment]
We will use Lily's vignette "Integrative Pathway Analysis with `pathwayPCA`" as the anchor vignette, then use the other 5-6 chapters as supplemental material.

**Comment by gabrielodom** [comment]
Please leave any website edit requests as comments here.

**Comment by gabrielodom** [comment]
We need to move the vignettes back into the `vignettes/` directory

**Comment by gabrielodom** [comment]
I've also re-organized the reference page.

**Comment by gabrielodom** [comment]
Website, news, and manual updated.

**Comment by lxw391** [comment]
@gabrielodom I've updated the main website Introduction paragraph, can you also update the package website https://gabrielodom.github.io/pathwayPCA/ Introduction section to match those in the main website?

**Comment by gabrielodom** [comment]
Neither the home page nor the integrative pathway analysis vignette say how to install the package.

**Comment by gabrielodom** [comment]
From @lxw391: Add instructions for stable and devel package versions to the website.

**Comment by gabrielodom** [comment]
From @lxw391:

Hi Gabriel, 

I was looking at the pathwayPCA website http://master.bioconductor.org/packages/devel/bioc/html/pathwayPCA.html today. Could you make some changes to the description? 

Currently we have 
“Apply the Supervised PCA and Adaptive, Elastic-Net, Sparse PCA methods to extract principal components from each pathway. Use these pathway- specific principal components as the design matrix relating the response to each pathway. Return the model fit statistic p-values, and adjust these values for False Discovery Rate. Return a data frame of the pathways sorted by their adjusted p-values. This package has corresponding vignettes hosted in the ''User Guides'' page of , and the website for the development information is hosted at .”

Please change this to: 
pathwayPCA is an integrative analysis tool that implements the principal component analysis (PCA) based pathway analysis approaches described in Chen et al. (2008), Chen et al. (2010), and Chen (2011). pathwayPCA allows users to: (1) Test pathway association with binary, continuous, or survival phenotypes. (2) Extract relevant genes in the pathways using the SuperPCA and AESPCA approaches. (3) Compute principal components (PCs) based on the selected genes. These estimated latent variables represent pathway activities for individual subjects, which can then be used to perform integrative pathway analysis, such as multi-omics analysis. (4) Extract relevant genes that drive pathway significance as well as data corresponding to these relevant genes for additional in-depth analysis. (5) Perform analyses with enhanced computational efficiency with parallel computing and enhanced data safety with S4-class data objects. (6) Analyze studies with complex experimental designs, with multiple covariates, and with interaction effects, e.g., testing whether pathway association with clinical phenotype is different between male and female subjects.

Also please add references Chen (2008), (2010) and (2011) to the reference list. 

The website link for the first reference included right now does not work. 

For the vignettes, please add numbers to file name and order them as done in https://www.bioconductor.org/packages/release/bioc/html/GenomicRanges.html

Also I think we might want to upload the paper to https://www.biorxiv.org/ to occupy research space. 

Thanks, 

-Lily

**Comment by gabrielodom** [comment]
Check the NEWS.md file formatting with

    tools:::.build_news_db_from_package_NEWS_md("NEWS.md")

**Comment by gabrielodom** [comment]
I think we're fine on this.
