### ISSUE TITLE
AESPCA_pvals and superPCA_pvals: update message to reflect parametric version

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#59]
when numReps = 0, need to update function to reflect parametric function is used for "Part 2: ..."

![image](https://user-images.githubusercontent.com/27868862/49330768-5adf0c00-f561-11e8-8703-bbf9a6438a8e.png)

**Comment by gabrielodom** [comment]
Steven: "make `numReps = 0` the default setting".
