### ISSUE TITLE
vignette example - multiOmics example - dataset

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#60]
If we're to also illustrate copy number analysis, we'll need to save CNV data in the package, right? 

since reading in CNV data took a long time, consider saving it as an RDS data in /data?

**Comment by lxw391** [comment]
We will also need to save phenotype file and rnaseq data for KIRP example in the pacakge, 
- the merged dataset "KIRP_HiSeq_inner.csv" at ~\Ban and Odom - Bioconductor Package\Example Data\Xena Interaction Kidney\data

- or should we read in the estimated PCs directly?

**Comment by gabrielodom** [comment]
@lxw391, please comment here with the detailed file names or object names you would like included in the vignette data. From inspecting you vignette, it appears that you need

- `ovCNV_aespcOut` (page 8)
- `KIRP_HiSeq_inner.csv` (page11)

Will these work? Any others?

**Comment by lxw391** [comment]
- for interaction example
let's save kidney data (`kidney_df`)  in .RDS format, it's much faster to read that in
let's also save aespcOut.RDS to save computing time

- for multi-omics example
save CNV data (`copyNumberClean_df`) in .RDS format, it only took 0.4 sec to read in the .RDS file on my computer 
also save ovCNV_aespcOut.RDS

**Comment by gabrielodom** [comment]
Based on the vignette edits, I've added the ovarian copy number data (`OV_surv_x_CNV2.RDS`) and kidney RNAseq data (`KIRP_Surv_RNAseq_inner.RDS`) to `inst/extdata/`.
