### ISSUE TITLE
function createOmics

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#84]
createOmics fail to show message that `There is 0 sample shared by the assay and phenotype data.`

the assay data has sample column
`head(ovmRNA_df$Sample)
[1] "TCGA-24-1850-01A-01R-1567-13" "TCGA-61-2104-01A-01R-1568-13" "TCGA-24-1470-01A-01R-1566-13" "TCGA-61-1741-01A-02R-1567-13"
[5] "TCGA-24-2023-01A-01R-1567-13" "TCGA-13-0762-01A-01R-1564-13"`

the response has sample column 
` Sample   <chr>   
 1 TCGA-3P-A9WA
 2 TCGA-59-A5PD
 3 TCGA-5X-AA5U
 4 TCGA-04-1331
 5 TCGA-04-1332
 6 TCGA-04-1335
 7 TCGA-04-1336
 8 TCGA-04-1337
 9 TCGA-04-1338
10 TCGA-04-1341`

**Comment by gabrielodom** [comment]
The TCGA barcodes are not in the same form between assay and response. Your assay data is using a 22-digit barcode, while the response sample ID is using a 10-digit barcode.
