### ISSUE TITLE
CreateOmics not reading all features of assay data

### ISSUE THREAD

**Issue by cfrasier** [gabrielodom/pathwayPCA#90]
I'm currently trying to create an Omics object using assay (gene expression) and phenotype (survival) data stored in a tidy dataframe. The assay data has around 38000 features (genes), yet the omics object is only recognizing 29 of those features. I am using the wikipathways pathway collection and I have made sure that many of the genes that are not being recognized are part of those pathways. I can find no differences in the assay dataframe to suggest why some genes would be recognized and others would not. Perhaps you can help share some insight?

The code used to create the Omics object
![image](https://user-images.githubusercontent.com/43578696/84929790-54aa7500-b09e-11ea-8ed2-1808b595f597.png)

The output from the script detailing the creation of the Omics object
![image](https://user-images.githubusercontent.com/43578696/84929744-42c8d200-b09e-11ea-800d-d3ec5e7b9f9a.png)

A 5x5 tibble of the assay dataframe
![image](https://user-images.githubusercontent.com/43578696/84929915-81f72300-b09e-11ea-85f9-8a7ed3f8fb3c.png)

Thanks,
Connor Frasier

**Comment by gabrielodom** [comment]
Hi Connor,
Please forgive me. I somehow missed this notification.
The diagnostic message states that your `allData` object only has 29 features. Is it possible that some of your columns are nested? Could you show me the output of `colnames(allData)` and `str(allData)`?

**Comment by cfrasier** [comment]
Hey, no worries, a late response is better than no response. So this is a small snapshot of colnames(allData):
![image](https://user-images.githubusercontent.com/43578696/92154735-43971780-edf4-11ea-849d-57a5953ecc1f.png)

And here is a snapshot of str(allData):
![image](https://user-images.githubusercontent.com/43578696/92154916-9244b180-edf4-11ea-8feb-4506757aa66f.png)

I also wrote the output to a file for you to peruse.
[PathwayPCA.output.txt](https://github.com/gabrielodom/pathwayPCA/files/5170624/PathwayPCA.output.txt)

**Comment by gabrielodom** [comment]
Ok, I have no earthly idea then. Do you have time for a Zoom call or something?

**Comment by cfrasier** [comment]
Yeah, absolutely. You can send the invite to my email: cfrasier@uncc.edu. I'm busy this afternoon, but I will be free all day tomorrow.

**Comment by gabrielodom** [comment]
Ok, so we found that the diagnostic messages of the `CreateOmics()` function has its header removed if there are more than a few thousand genes printed via either "improper gene names" or "variance of genes = 0" messages. I should add a catch that prevents more than 1000 genes being printed by the message.
