### ISSUE TITLE
system.file() function 

### ISSUE THREAD

**Issue by Prometheus405** [gabrielodom/pathwayPCA#95]
Im trying to load .gmt file into my project. Unfortunately function system.file() can't find my file. 
Pathway file has been downloaded from MSigDB - curated gene sets. 
I tried adding path to file and still no success.

`gmt_path <- system.file('extdata', 'c2.all.v2022.1.Hs.entrez.gmt', package = "pathwayPCA" ,mustWork = TRUE)`

**Comment by gabrielodom** [comment]
Issue resolved here: <https://support.bioconductor.org/p/9147504/>
